Repository getupio-undistro/undistro, pull requests merged in 2021-04, with the labels that each got.

#105 add config for codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/common-debian.sh
  .devcontainer/library-scripts/docker-debian.sh
  .devcontainer/library-scripts/go-debian.sh
  .devcontainer/library-scripts/node-debian.sh
Labels: approved, size/XL

#106 all: update dependency
  cmd/undistro/main.go
  go.mod
  go.sum
  pkg/cli/config.go
  pkg/cloud/aws/cloudformation/service.go
  pkg/helm/repository_test.go
  pkg/test/envtest.go
Labels: approved, size/L

#108 UnDistro API server with proxy
  cmd/undistroapiserver/main.go
  go.mod
  go.sum
  pkg/cli/get.go
  pkg/fs/frontend/.gitkeep
  pkg/fs/fs.go
  pkg/kube/client.go
  pkg/kube/proxy.go
  pkg/kube/proxy_test.go
  pkg/undistro/apiserver/health/health.go
  pkg/undistro/apiserver/health/health_test.go
  pkg/undistro/apiserver/proxy/handler.go
  pkg/undistro/apiserver/server.go
Labels: approved, lgtm, size/XL

#111 Policies
  .prow/images/e2e/Dockerfile
  PROJECT
  apis/app/v1alpha1/cluster_types.go
  apis/app/v1alpha1/defaultpolicies_types.go
  apis/app/v1alpha1/helmrelease_types.go
  apis/app/v1alpha1/helmrelease_webhook.go
  apis/app/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/app.undistro.io_defaultpolicies.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_defaultpolicies.yaml
  config/crd/patches/webhook_in_defaultpolicies.yaml
  config/manager/kustomization.yaml
  config/rbac/defaultpolicies_editor_role.yaml
  config/rbac/defaultpolicies_viewer_role.yaml
  config/samples/app_v1alpha1_defaultpolicies.yaml
  controllers/app/defaultpolicies_controller.go
  controllers/app/helmrelease_controller.go
  controllers/app/suite_test.go
  main.go
  pkg/fs/apps/kyverno.yaml
  pkg/fs/fs.go
  pkg/fs/policies/disallow-add-capabilities.yaml
  pkg/fs/policies/disallow-default-namespace.yaml
  pkg/fs/policies/disallow-delete-kyverno.yaml
  pkg/fs/policies/disallow-host-namespace.yaml
  pkg/fs/policies/disallow-host-path.yaml
  pkg/fs/policies/disallow-host-port.yaml
  pkg/fs/policies/disallow-latest-tag.yaml
  pkg/fs/policies/require-resources.yaml
  pkg/helm/runner.go
  pkg/meta/conditions.go
  pkg/test/envtest.go
Labels: approved, size/XXL

#115 back to gh-action
  .github/workflows/build.yml
  goreleaser.yml
  hack/version.sh
Labels: approved, lgtm, size/M

#114 Make region immutable
  apis/app/v1alpha1/cluster_webhook.go
  pkg/fs/apps/kyverno.yaml
Labels: size/S

#116 add new create cluster command
  apis/app/v1alpha1/cluster_webhook.go
  pkg/cli/create.go
  pkg/cli/undistro.go
  pkg/cloud/aws/aws.go
  pkg/cloud/setup.go
  pkg/fs/defaultarch/aws.yaml
  pkg/fs/fs.go
Labels: approved, do-not-merge/work-in-progress, size/L

#118 add ci config for website deploy
  .github/workflows/merge-lgtm.yml
  .github/workflows/release-website-hlg.yml
  .github/workflows/release-website-prd.yml
  website/package.json
Labels: lgtm

#122 fix defaultpolicies crd
  charts/undistro/Chart.yaml
  charts/undistro/crds/undistro.yaml
  charts/undistro/values.yaml
  config/crd/patches/webhook_in_defaultpolicies.yaml
  main.go
Labels: lgtm

#126 push charts during release
  .github/workflows/undistro-release.yml
Labels: lgtm
