Repository getupio-undistro/undistro, pull requests merged in 2021-07, with the labels that each got.

#250 Auto HTTPS to local domains
  charts/ingress-nginx/values.yaml
  charts/undistro/templates/ingress.yaml
  charts/undistro/templates/local-issuer.yaml
  charts/undistro/templates/prod-clusterissuer.yaml
  charts/undistro/values.yaml
  go.mod
  go.sum
  pkg/cli/config.go
  pkg/cli/install.go
  pkg/internalautohttps/truster.go
  pkg/undistro/undistro.go
Labels: kind/feature

#251 Helm lint & test action
  .github/workflows/build.yml
  charts/calico/Chart.yaml
  charts/cert-manager/Chart.yaml
  charts/cluster-api/Chart.yaml
  charts/ingress-nginx/Chart.yaml
  charts/ingress-nginx/values.yaml
  charts/pinniped-concierge/Chart.yaml
  charts/pinniped-supervisor/Chart.yaml
  charts/undistro-aws/Chart.yaml
  charts/undistro/Chart.yaml
  charts/undistro/templates/ingress.yaml
  charts/undistro/templates/local-issuer.yaml
  charts/undistro/values.yaml
Labels: bug, enhancement

#253 added paused condition
  apis/app/v1alpha1/cluster_types.go
  apis/app/v1alpha1/defaultpolicies_types.go
  apis/app/v1alpha1/helmrelease_types.go
  apis/app/v1alpha1/webhook_suite_test.go
  apis/config/v1alpha1/provider_types.go
  apis/config/v1alpha1/webhook_suite_test.go
  controllers/app/cluster_controller.go
  controllers/app/defaultpolicies_controller.go
  controllers/app/helmrelease_controller.go
  controllers/config/provider_controller.go
  controllers/config/suite_test.go
  pkg/meta/conditions.go
Labels: lgtm

#254 Chart and CLI refactor
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .gitignore
  Makefile
  PROJECT
  apis/config/v1alpha1/groupversion_info.go
  apis/config/v1alpha1/provider_types.go
  apis/config/v1alpha1/provider_webhook.go
  apis/config/v1alpha1/webhook_suite_test.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  aws-init.docker
  charts/cluster-api/templates/kubeadm-bootstrap.yaml
  charts/cluster-api/templates/kubeadm-controlplane.yaml
  charts/undistro-aws/templates/controlplane.yaml
  charts/undistro-aws/templates/credentials.yaml
  charts/undistro-aws/templates/infrastructure.yaml
  charts/undistro-aws/values.yaml
  charts/undistro/Chart.yaml
  charts/undistro/crds/undistro.yaml
  charts/undistro/templates/credentials.yaml
  charts/undistro/templates/undistro.yaml
  charts/undistro/values.yaml
  cmd/aws-init/main.go
  config/crd/bases/config.undistro.io_providers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_providers.yaml
  config/crd/patches/webhook_in_providers.yaml
  config/rbac/provider_editor_role.yaml
  config/rbac/provider_viewer_role.yaml
  config/samples/config_v1alpha1_provider.yaml
  config/webhook/manifests.yaml
  controllers/config/provider_controller.go
  controllers/config/suite_test.go
  e2e/main_test.go
  go.mod
  go.sum
  goreleaser.yml
  main.go
  pkg/cli/config.go
  pkg/cli/install.go
  pkg/cli/move.go
  pkg/cli/undistro.go
  pkg/cli/upgrade.go
  pkg/cloud/aws/aws.go
  pkg/cloud/aws/instancetypes.json
  pkg/cloud/setup.go
  pkg/fs/chart/.gitkeep
  pkg/fs/fs.go
  pkg/graph/graph.go
  pkg/internalautohttps/truster.go
  pkg/scheme/scheme.go
  pkg/test/envtest.go
  pkg/undistro/apiserver/provider/infra/aws/aws.go
  pkg/undistro/apiserver/provider/infra/infra.go
  pkg/undistro/apiserver/provider/provider.go
  pkg/undistro/apiserver/provider/provider_test.go
  pkg/undistro/apiserver/server.go
  testbin/docker-build-e2e.sh
  website/src/util/docs/index.md
Labels: lgtm, size/XXL

#257 update capi to 0.3.21 and capa to 0.6.7
  charts/cluster-api/Chart.yaml
  charts/cluster-api/templates/cluster-api.yaml
  charts/cluster-api/templates/kubeadm-bootstrap.yaml
  charts/cluster-api/templates/kubeadm-controlplane.yaml
  charts/undistro-aws/Chart.yaml
  charts/undistro-aws/templates/bootstrap.yaml
  charts/undistro-aws/templates/controlplane.yaml
  charts/undistro-aws/templates/infrastructure.yaml
  pkg/cloud/aws/cloudformation/cloudformation.go
Labels: lgtm

#259 Metadata APIs
  .devcontainer/Dockerfile
  PROJECT
  apis/metadata/v1alpha1/awsmachine_types.go
  apis/metadata/v1alpha1/flavor_types.go
  apis/metadata/v1alpha1/groupversion_info.go
  apis/metadata/v1alpha1/provider_types.go
  apis/metadata/v1alpha1/zz_generated.deepcopy.go
  charts/cluster-api/Chart.yaml
  charts/cluster-api/templates/cluster-api.yaml
  charts/cluster-api/templates/kubeadm-bootstrap.yaml
  charts/cluster-api/templates/kubeadm-controlplane.yaml
  charts/undistro-aws/Chart.yaml
  charts/undistro-aws/templates/bootstrap.yaml
  charts/undistro-aws/templates/controlplane.yaml
  charts/undistro-aws/templates/infrastructure.yaml
  charts/undistro/crds/undistro.yaml
  config/crd/bases/metadata.undistro.io_awsmachines.yaml
  config/crd/bases/metadata.undistro.io_flavors.yaml
  config/crd/bases/metadata.undistro.io_providers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_awsmachines.yaml
  config/crd/patches/cainjection_in_flavors.yaml
  config/crd/patches/cainjection_in_providers.yaml
  config/crd/patches/webhook_in_awsmachines.yaml
  config/crd/patches/webhook_in_flavors.yaml
  config/crd/patches/webhook_in_providers.yaml
  config/rbac/awsmachine_editor_role.yaml
  config/rbac/awsmachine_viewer_role.yaml
  config/rbac/flavor_editor_role.yaml
  config/rbac/flavor_viewer_role.yaml
  config/rbac/provider_editor_role.yaml
  config/rbac/provider_viewer_role.yaml
  config/samples/metadata_v1alpha1_awsmachine.yaml
  config/samples/metadata_v1alpha1_flavor.yaml
  config/samples/metadata_v1alpha1_provider.yaml
  controllers/metadata/provider_controller.go
  controllers/metadata/suite_test.go
  main.go
  pkg/cli/install.go
  pkg/cloud/aws/aws.go
  pkg/cloud/setup.go
  pkg/internalautohttps/truster.go
  pkg/meta/labels.go
  pkg/meta/reconcile.go
  pkg/scheme/scheme.go
Labels: lgtm

#261 convert memory and vcpus from float to string
  pkg/cloud/aws/instancetypes.json
Labels: kind/feature

#264 fix install order
  pkg/cli/install.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: lgtm

#266 fix duplicate install
  charts/undistro/Chart.yaml
  charts/undistro/values.yaml
  pkg/cli/install.go
Labels: lgtm

#277 update capa to 0.6.8
  charts/undistro-aws/Chart.yaml
  charts/undistro-aws/templates/bootstrap.yaml
  charts/undistro-aws/templates/controlplane.yaml
  charts/undistro-aws/templates/infrastructure.yaml
  pkg/util/util_test.go
Labels: lgtm
