Repository getupio-undistro/undistro, pull requests merged in 2021-11, with the labels that each got.

#363 fix deletion cluster in openstack
  controllers/app/cluster_controller.go
  controllers/app/helmrelease_controller.go
Labels: bug

#362 better changelog
  .github/release.yml
  goreleaser.yml
Labels: enhancement

#364 Object instance patch refactor
  charts/undistro-aws/values.yaml
  charts/undistro/Chart.yaml
  charts/undistro/values.yaml
  controllers/app/cluster_controller.go
  controllers/app/defaultpolicies_controller.go
  controllers/app/helmrelease_controller.go
  controllers/app/helpers.go
  controllers/app/identity_controller.go
  controllers/app/observer_controller.go
Labels: refactor

#366 add move label on audience secret
  apis/app/v1alpha1/helmrelease_webhook.go
  pkg/undistro/undistro.go
Labels: bug

#365 Warnings
  UI/package.json
  UI/yarn.lock
Labels: dependencies, javascript

#367 Add logs in cluster controller flow
  controllers/app/cluster_controller.go
  controllers/app/identity_controller.go
  controllers/app/observer_controller.go
Labels: refactor

#368 Fix DefaultPolicies installation
  charts/undistro-aws/values.yaml
  charts/undistro/Chart.yaml
  charts/undistro/values.yaml
  controllers/app/cluster_controller.go
  controllers/app/defaultpolicies_controller.go
Labels: bug

#370 fix GHSA-mc8v-mgrf-8f4m and GHSA-5j5w-g665-5m35 vulnerabilities
  go.mod
  go.sum
Labels: dependencies

#371 Improve logs strategy
  .github/release.yml
  controllers/app/cluster_controller.go
  controllers/app/defaultpolicies_controller.go
  controllers/app/helmrelease_controller.go
  controllers/app/identity_controller.go
  controllers/app/observer_controller.go
  controllers/app/suite_test.go
  controllers/metadata/provider_controller.go
  main.go
  pkg/controllerlib/lib.go
Labels: refactor

#372 Replace default ubuntu Actions Runner by self-hosted runner in E2E jobs
  .github/workflows/e2e-aws-1.19.yml
  .github/workflows/e2e-aws-1.20.yml
  .github/workflows/e2e-aws-1.21.yml
  .github/workflows/e2e-aws-1.22.yml
  .github/workflows/prow.yml
Labels: enhancement

#374 Remove kind installation from E2E flow
  .github/workflows/e2e-aws-1.19.yml
  .github/workflows/e2e-aws-1.20.yml
  .github/workflows/e2e-aws-1.21.yml
  .github/workflows/e2e-aws-1.22.yml
  controllers/app/helmrelease_controller.go
Labels: refactor
