Repository getupio-undistro/undistro, pull requests merged in 2021-12, with the labels that each got.

#381 Fix bug when change spec
  controllers/app/cluster_controller.go
  pkg/fs/clustertemplates/aws/ec2.yaml
  pkg/fs/clustertemplates/aws/eks.yaml
  pkg/fs/clustertemplates/openstack/openstack.yaml
  pkg/template/template.go
  pkg/util/util.go
Labels: bug

#394 docs: add new sections to readme
  README.md
  assets/undistro-header.png
  assets/undistro.svg
Labels: documentation

#403 Deps: bump runc to v1.0.3
  go.mod
  go.sum
Labels: dependencies

#399 Initial implementation of cluster-autoscaler for openstack
  .github/workflows/undistro-release.yml
  charts/cluster-autoscaler/.helmignore
  charts/cluster-autoscaler/Chart.yaml
  charts/cluster-autoscaler/README.md
  charts/cluster-autoscaler/README.md.gotmpl
  charts/cluster-autoscaler/templates/NOTES.txt
  charts/cluster-autoscaler/templates/_helpers.tpl
  charts/cluster-autoscaler/templates/clusterrole.yaml
  charts/cluster-autoscaler/templates/clusterrolebinding.yaml
  charts/cluster-autoscaler/templates/deployment.yaml
  charts/cluster-autoscaler/templates/pdb.yaml
  charts/cluster-autoscaler/templates/podsecuritypolicy.yaml
  charts/cluster-autoscaler/templates/priority-expander-configmap.yaml
  charts/cluster-autoscaler/templates/prometheusrule.yaml
  charts/cluster-autoscaler/templates/role.yaml
  charts/cluster-autoscaler/templates/rolebinding.yaml
  charts/cluster-autoscaler/templates/secret.yaml
  charts/cluster-autoscaler/templates/service.yaml
  charts/cluster-autoscaler/templates/serviceaccount.yaml
  charts/cluster-autoscaler/templates/servicemonitor.yaml
  charts/cluster-autoscaler/values.yaml
  controllers/app/cluster_controller.go
  controllers/app/helmrelease_controller.go
  pkg/fs/clustertemplates/openstack/openstack.yaml
  pkg/fs/defaultarch/openstack.yaml
  pkg/meta/conditions.go
  pkg/meta/labels.go
Labels: enhancement

#412 Extract <meta>, <record> and <controllerlib> packages as components.
  apis/app/v1alpha1/cluster_types.go
  apis/app/v1alpha1/cluster_webhook.go
  apis/app/v1alpha1/defaultpolicies_types.go
  apis/app/v1alpha1/defaultpolicies_webhook.go
  apis/app/v1alpha1/helmrelease_types.go
  apis/app/v1alpha1/helmrelease_webhook.go
  apis/app/v1alpha1/identity_types.go
  apis/app/v1alpha1/observer_types.go
  apis/metadata/v1alpha1/provider_types.go
  config/crd/bases/app.undistro.io_identities.yaml
  controllers/app/cluster_controller.go
  controllers/app/defaultpolicies_controller.go
  controllers/app/helmrelease_controller.go
  controllers/app/identity_controller.go
  controllers/app/observer_controller.go
  controllers/metadata/provider_controller.go
  e2e/1.19/aws/ec2-19_test.go
  e2e/1.20/aws/ec2-20_test.go
  e2e/1.21/aws/ec2-21_test.go
  e2e/1.22/aws/ec2-22_test.go
  go.mod
  go.sum
  main.go
  pkg/cli/config.go
  pkg/cli/install.go
  pkg/cli/move.go
  pkg/cli/setup.go
  pkg/cloud/openstack/openstack.go
  pkg/controllerlib/lib.go
  pkg/graph/graph.go
  pkg/hr/helmrelease_client.go
  pkg/meta/conditions.go
  pkg/meta/labels.go
  pkg/meta/reconcile.go
  pkg/record/record.go
  pkg/undistro/undistro.go
Labels: enhancement
