Repository getupio-undistro/undistro, pull requests merged in 2021-05, with the labels that each got.

#138 Fix CAPI condition
  controllers/app/cluster_controller.go
  examples/manage-network-traffic.yaml
Labels: bug

#148 Create cluster part 1
  UI/package.json
  UI/src/App.tsx
  UI/src/assets/font-icon/icons.css
  UI/src/assets/font-icon/icons.eot
  UI/src/assets/font-icon/icons.json
  UI/src/assets/font-icon/icons.svg
  UI/src/assets/font-icon/icons.ttf
  UI/src/assets/font-icon/icons.woff
  UI/src/assets/font-icon/icons.woff2
  UI/src/assets/font-icon/index.html
  UI/src/assets/icons/close.svg
  UI/src/assets/images/advanced.svg
  UI/src/assets/images/background.png
  UI/src/assets/images/logo.svg
  UI/src/assets/images/wizard.svg
  UI/src/components/button/index.scss
  UI/src/components/button/index.tsx
  UI/src/components/dropdownMenu/index.scss
  UI/src/components/input/index.scss
  UI/src/components/input/index.tsx
  UI/src/components/itemSideMenu/index.scss
  UI/src/components/menuSideBar/index.scss
  UI/src/components/menuTopBar/index.scss
  UI/src/components/select/index.scss
  UI/src/components/select/index.tsx
  UI/src/components/toggle/index.scss
  UI/src/components/toggle/index.tsx
  UI/src/index.tsx
  UI/src/modals/createCluster/clusterAdvanced.tsx
  UI/src/modals/createCluster/clusterWizard.tsx
  UI/src/modals/createCluster/createCluster.tsx
  UI/src/modals/createCluster/steps.tsx
  UI/src/modals/default.tsx
  UI/src/modals/index.scss
  UI/src/modals/index.tsx
  UI/src/modals/store.tsx
  UI/src/routes/home/index.scss
  UI/src/routes/home/index.tsx
  UI/src/styles/_theme.scss
  UI/src/styles/app.scss
  UI/src/util/api/cluster.tsx
  UI/src/util/api/index.tsx
  UI/src/util/api/node.tsx
  UI/src/util/api/provider.tsx
  UI/src/util/api/secret.tsx
  UI/src/util/modals.tsx
  UI/tsconfig.extends.json
  UI/yarn.lock
Labels: area/GUI, kind/feature

#151 E2E ec2
  .github/workflows/e2e.yml
  Tiltfile
  charts/kyverno/Chart.yaml
  charts/undistro-aws/Chart.yaml
  charts/undistro-aws/templates/bootstrap.yaml
  charts/undistro-aws/templates/controlplane.yaml
  charts/undistro-aws/templates/infrastructure.yaml
  e2e/ec2_test.go
  e2e/main_test.go
  e2e/testdata/ec2-cluster.yaml
  e2e/testdata/ec2-policies.yaml
  go.mod
  go.sum
  pkg/fs/apps/kyverno.yaml
  pkg/undistro/apiserver/server.go
  tilt.docker
Labels: lgtm

#152 Endpoint to retrieve provider metadata
  apis/app/v1alpha1/cluster_types.go
  apis/app/v1alpha1/zz_generated.deepcopy.go
  apis/config/v1alpha1/provider_types.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  charts/undistro/Chart.yaml
  charts/undistro/crds/undistro.yaml
  charts/undistro/values.yaml
  config/crd/bases/config.undistro.io_providers.yaml
  e2e/main_test.go
  hack/boilerplate.go.txt
  pkg/cli/install.go
  pkg/undistro/apiserver/health/health.go
  pkg/undistro/apiserver/provider/aws/aws.go
  pkg/undistro/apiserver/provider/aws/instancetypesaws.json
  pkg/undistro/apiserver/provider/provider.go
  pkg/undistro/apiserver/provider/provider_test.go
  pkg/undistro/apiserver/server.go
  pkg/undistro/undistro.go
Labels: area/provider, do-not-merge/work-in-progress, hold, kind/feature

#155 Endpoint to retrieve aws account ssh keys by region
  apis/config/v1alpha1/provider_types.go
  apis/config/v1alpha1/provider_webhook.go
  pkg/cli/install.go
  pkg/cloud/aws/aws.go
  pkg/undistro/apiserver/provider/aws/aws.go
  pkg/undistro/apiserver/provider/infra/aws.go
  pkg/undistro/apiserver/provider/infra/instancetypesaws.json
  pkg/undistro/apiserver/provider/provider.go
  pkg/undistro/apiserver/provider/provider_test.go
  pkg/undistro/apiserver/server.go
  pkg/undistro/apiserver/util/util.go
Labels: area/provider, kind/feature

#159 Refact provider metadata endpoint
  pkg/meta/reconcile.go
  pkg/undistro/apiserver/provider/infra/aws/aws.go
  pkg/undistro/apiserver/provider/infra/aws/instancetypesaws.json
  pkg/undistro/apiserver/provider/infra/infra.go
  pkg/undistro/apiserver/provider/provider.go
  pkg/undistro/apiserver/provider/provider_test.go
  pkg/undistro/apiserver/server.go
  pkg/undistro/apiserver/util/util.go
Labels: area/provider, kind/feature, ¯\_(ツ)_/¯

#160 add tls passthrough in undistro ingress
  charts/undistro/templates/ingress.yaml
Labels: kind/feature

#164 Fix showprogress command
  charts/undistro/Chart.yaml
  charts/undistro/templates/ingress.yaml
  charts/undistro/values.yaml
  pkg/cli/showprogress.go
  pkg/undistro/apiserver/proxy/handler.go
  pkg/undistro/apiserver/server.go
Labels: kind/bug
