Repository getupio-undistro/undistro, pull requests merged in 2021-08, with the labels that each got.

#285 Minor script improvements
  hack/cluster.sh
  testbin/docker-build-e2e.sh
Labels: lgtm

#291 Hotfix in get kubeconfig command when no cluster name is passed (without the --admin flag)
  charts/undistro/Chart.yaml
  charts/undistro/values.yaml
  pkg/cli/get.go
Labels: bug, lgtm

#292 [skip e2e] add auth command to undistro cli
  go.sum
  pkg/cli/undistro.go
  website/src/util/docs/identity.md
Labels: enhancement, lgtm

#293 acme certificate does not support internal ip
  charts/undistro/templates/identityingress.yaml
  charts/undistro/templates/localissuer.yaml
  charts/undistro/templates/ui-ingress.yaml
  charts/undistro/values.yaml
Labels: bug, kind/bug

#294 fix remote cluster bug
  charts/undistro-aws/values.yaml
  charts/undistro/Chart.yaml
  charts/undistro/values.yaml
  controllers/app/identity_controller.go
  pkg/cli/config.go
Labels: lgtm

#295 Detail identity docs
  charts/undistro/Chart.yaml
  charts/undistro/templates/identitysecret.yaml
  charts/undistro/values.yaml
  website/src/util/docs/identity.md
  website/src/util/markdownNavigation.js
Labels: documentation, lgtm

#303 [skip e2e] add cla bot
  README.md
Labels: lgtm
