Repository getupio-undistro/undistro, pull requests merged in 2022-01, with the labels that each got.

#417 Cluster deletion never ending
  apis/app/v1alpha1/cluster_webhook.go
  apis/app/v1alpha1/err_messages.go
  charts/undistro/templates/observer.yaml
  charts/undistro/values.yaml
  controllers/app/cluster_controller.go
  controllers/app/helmrelease_controller.go
  go.mod
  go.sum
  pkg/cli/move.go
Labels: bug

#418 Increase patch version in containerd/containerd to avoid CVE-2021-43816
  go.mod
  go.sum
Labels: enhancement, security

#420 deps: bump node-forge to v1.2
  website/package-lock.json
Labels: dependencies

#424 Refactor e2e tests to use <clilib>.
  e2e/1.19/aws/ec2-19_test.go
  e2e/1.19/aws/helm_test.go
  e2e/1.19/aws/install_test.go
  e2e/1.19/aws/main_test.go
  e2e/1.20/aws/ec2-20_test.go
  e2e/1.20/aws/helm_test.go
  e2e/1.20/aws/install_test.go
  e2e/1.20/aws/main_test.go
  e2e/1.21/aws/ec2-21_test.go
  e2e/1.21/aws/helm_test.go
  e2e/1.21/aws/install_test.go
  e2e/1.21/aws/main_test.go
  e2e/1.22/aws/ec2-22_test.go
  e2e/1.22/aws/helm_test.go
  e2e/1.22/aws/install_test.go
  e2e/1.22/aws/main_test.go
  go.mod
  go.sum
Labels: enhancement

#422 Add backup workflow
  .github/workflows/backup.yml
Labels: enhancement
